/*
Package gomod GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package gomod

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v RevInfo) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Offset":
			return []string{}, true
		case "Short":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
