/*
Package ship GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package engine

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Build) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Workspaces":
			return []string{}, true
		case "Platforms":
			return []string{
				"Set target build platform",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
