/*
Package engine GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package engine

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Pipeline) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Action":
			return []string{}, true
		case "Plan":
			return []string{}, true
		case "Export":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
