/*
Package logutil GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package logutil

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (Attribute) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (LogLevel) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (v Logger) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "LogLevel":
			return []string{
				"Log level",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
