/*
Package spec GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package spec

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Package) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Pkg":
			return []string{}, true
		case "Platform":
			return []string{}, true
		case "Files":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Pkg, names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(v.Platform, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Pkg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Version":
			return []string{}, true
		case "Revision":
			return []string{}, true
		case "Description":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Platform) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Arch":
			return []string{}, true
		case "OS":
			return []string{}, true
		case "Variant":
			return []string{}, true
		case "OSVersion":
			return []string{}, true
		case "OSFeatures":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Ship) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Package":
			return []string{}, true
		case "Files":
			return []string{}, true
		case "Scripts":
			return []string{}, true
		case "Dependencies":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
